version: '3'

services:
  elasticsearch:
      build: ./elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"
      volumes:
        - es-data01:/usr/share/elasticsearch/data
      environment:
        - "discovery.zen.minimum_master_nodes=1"
        - "discovery.type=single-node"
        - "cluster.name=elasticsearch"
        - "network.host=0.0.0.0"  
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        - "XPACK_SECURITY_ENABLED=false"
      networks:
        - elk
      healthcheck:
        test: "curl http://elasticsearch:9200"
        interval: "1s"
        timeout: "3s"
        retries: 60
  web:
    build: ./web
    restart: always
    ports:
      - "4001:4001"
    environment:
      - "ELASTIC_URL=http://elasticsearch:9200"
    links:
        - elasticsearch
    depends_on:
      - elasticsearch
    networks:
        - elk    
networks:
  elk:
    driver: bridge

volumes:
  es-data01:
    driver: local
    #external: true

